from __future__ import annotations

"""WebUI translation support - independent from game locale.

Translations based on official Battle Cats TW locale files."""

from typing import Any

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "BCSFE": "BCSFE",
        "Save File Editor": "Save File Editor",
        "Save loaded": "Save loaded",
        "Save": "Save",
        "Items": "Items",
        "Cats": "Cats",
        "Map": "Map",
        "Gamatoto": "Gamatoto",
        "Account": "Account",
        "Fixes": "Fixes",
        "Other": "Other",
        "Seeds": "Seeds",
        "Config": "Config",
        "Open Save File": "Open Save File",
        "Select your SAVE_DATA file to begin editing.": "Select your SAVE_DATA file to begin editing.",
        "Choose file": "Choose file",
        "Load Save": "Load Save",
        "Download Save from Server": "Download Save from Server",
        "Enter your transfer code and confirmation code to download a save from the server.":
            "Enter your transfer code and confirmation code to download a save from the server.",
        "Download": "Download",
        "Transfer code": "Transfer code",
        "Confirmation code": "Confirmation code",
        "Save Management": "Save Management",
        "Download Save": "Download Save",
        "Export as JSON": "Export as JSON",
        "Upload to Server": "Upload to Server",
        "Close Save": "Close Save",
        "New Save": "New Save",
        "Convert Region": "Convert Region",
        "Convert Game Version": "Convert Game Version",
        "Upload Codes": "Upload Codes",
        "Currency": "Currency",
        "Cat Food": "Cat Food",
        "XP": "XP",
        "Tickets": "Tickets",
        "Normal Tickets": "Normal Tickets",
        "Rare Tickets": "Rare Tickets",
        "Platinum Tickets": "Platinum Tickets",
        "Legend Tickets": "Legend Tickets",
        "Platinum Shards": "Platinum Shards",
        "100M Tickets": "100M Tickets",
        "Rare Ticket NP Trade": "Rare Ticket NP Trade",
        "Resources": "Resources",
        "NP": "NP",
        "Leadership": "Leadership",
        "Golden CPU": "Golden CPU",
        "Reset": "Reset",
        "Catseyes": "Catseyes",
        "Catfruit": "Catfruit",
        "Catamins": "Catamins",
        "Battle Items": "Battle Items",
        "Make All Endless": "Make All Endless",
        "Other Items": "Other Items",
        "Edit Scheme Items": "Edit Scheme Items",
        "Edit Labyrinth Medals": "Edit Labyrinth Medals",
        "Edit Treasure Chests": "Edit Treasure Chests",
        "Edit Event Tickets": "Edit Event Tickets",
        "Bulk Actions": "Bulk Actions",
        "Unlock All Cats": "Unlock All Cats",
        "Max Upgrade All": "Max Upgrade All",
        "True Form All": "True Form All",
        "Fourth Form All": "Fourth Form All",
        "Max Talents All": "Max Talents All",
        "Unlock Cat Guide": "Unlock Cat Guide",
        "Get Obtainable Cats": "Get Obtainable Cats",
        "Get Unobtainable Cats": "Get Unobtainable Cats",
        "Reset Levels": "Reset Levels",
        "Lock All": "Discard All",
        "Includes abnormal cats, risk of ban": "Includes abnormal cats, risk of ban",
        "Cat Storage": "Cat Storage",
        "Edit Special Skills": "Edit Special Skills",
        "Unlocked Slots": "Unlocked Slots",
        "Map / Levels": "Map / Levels",
        "Main Story": "Main Story",
        "Clear Tutorial": "Clear Tutorial",
        "Clear All Story": "Clear All Story",
        "Max All Treasures": "Max All Treasures",
        "Clear All Outbreaks": "Clear All Outbreaks",
        "ITF Timed Scores": "ITF Timed Scores",
        "Filibuster Reclearing": "Filibuster Reclearing",
        "Advanced Chapters": "Advanced Chapters",
        "Clear Aku Realms": "Clear Aku Realms",
        "Unlock Aku Realm": "Unlock Aku Realm",
        "Clear Uncanny Legends": "Clear Uncanny Legends",
        "Clear Zero Legends": "Clear Zero Legends",
        "Clear Catamin Stages": "Clear Catamin Stages",
        "Behemoth Culling": "Behemoth Culling",
        "Catclaw Championships": "Catclaw Championships",
        "Events & Gauntlets": "Events & Gauntlets",
        "Clear SoL": "Clear SoL",
        "Clear Events": "Clear Events",
        "Clear Collab": "Clear Collab",
        "Clear Gauntlets": "Clear Gauntlets",
        "Collab Gauntlets": "Collab Gauntlets",
        "Clear Enigma Stages": "Clear Enigma Stages",
        "Towers & Scores": "Towers & Scores",
        "Clear Towers": "Clear Towers",
        "Clear Legend Quest": "Clear Legend Quest",
        "Challenge Score": "Challenge Score",
        "Dojo Score": "Dojo Score",
        "Edit Engineers": "Edit Engineers",
        "Edit Base Materials": "Edit Base Materials",
        "Gamatoto XP Level": "Gamatoto XP Level",
        "Gamatoto Helpers": "Gamatoto Helpers",
        "Ototo Cannon": "Ototo Cannon",
        "Cat Shrine": "Cat Shrine",
        "Upload Items": "Upload Items",
        "Unban Account": "Unban Account",
        "Inquiry Code": "Inquiry Code",
        "Fix Gamatoto Crash": "Fix Gamatoto Crash",
        "Fix Ototo Crash": "Fix Ototo Crash",
        "Fix Time Errors": "Fix Time Errors",
        "Fix Officer Pass Crash": "Fix Officer Pass Crash",
        "Unlock Equip Menu": "Unlock Equip Menu",
        "Reset Gambling Events": "Reset Gambling Events",
        "Set Restart Pack": "Set Restart Pack",
        "Edit Enemy Guide": "Edit Enemy Guide",
        "Edit User Rank Rewards": "Edit User Rank Rewards",
        "Edit Gold Pass": "Edit Gold Pass",
        "Edit Medals": "Edit Medals",
        "Edit Missions": "Edit Missions",
        "Playtime": "Playtime",
        "Own": "Own",
        "Set": "Set",
        "Gacha Seeds": "Gacha Seeds",
        "Rare Gatya Seed": "Rare Gatya Seed",
        "Normal Gatya Seed": "Normal Gatya Seed",
        "Event Gatya Seed": "Event Gatya Seed",
        "Configuration": "Configuration",
        "Save Config": "Save Config",
        "Enabled": "Enabled",
        "Disabled": "Disabled",
        "Convert": "Convert",
        "UI Language": "UI Language",
    },
    "zh-Hant": {
        "BCSFE": "BCSFE",
        "Save File Editor": "存檔編輯器",
        "Save loaded": "已載入存檔",
        "Save": "存檔",
        "Items": "道具",
        "Cats": "貓咪",
        "Map": "關卡",
        "Gamatoto": "加碼多多",
        "Account": "帳號",
        "Fixes": "修正",
        "Other": "其他",
        "Seeds": "轉蛋種子",
        "Config": "設定",
        "Open Save File": "開啟存檔",
        "Select your SAVE_DATA file to begin editing.": "選擇你的 SAVE_DATA 檔案開始編輯。",
        "Choose file": "選擇檔案",
        "Load Save": "載入存檔",
        "Download Save from Server": "從伺服器下載存檔",
        "Enter your transfer code and confirmation code to download a save from the server.":
            "輸入引繼碼和確認碼從伺服器下載存檔。",
        "Download": "下載",
        "Transfer code": "引繼碼",
        "Confirmation code": "確認碼",
        "Save Management": "存檔管理",
        "Download Save": "下載存檔",
        "Export as JSON": "匯出 JSON",
        "Upload to Server": "上傳到伺服器",
        "Close Save": "關閉存檔",
        "New Save": "新存檔",
        "Convert Region": "轉換區域",
        "Convert Game Version": "轉換遊戲版本",
        "Upload Codes": "上傳碼",
        "Currency": "貨幣",
        "Cat Food": "貓罐頭",
        "XP": "XP(經驗值)",
        "Tickets": "轉蛋券",
        "Normal Tickets": "基本轉蛋券",
        "Rare Tickets": "稀有券",
        "Platinum Tickets": "白金券",
        "Legend Tickets": "傳說券",
        "Platinum Shards": "白金券碎片",
        "100M Tickets": "一億次下載紀念券",
        "Rare Ticket NP Trade": "稀有券兌換",
        "Resources": "資源",
        "NP": "NP",
        "Leadership": "首領旗",
        "Golden CPU": "重置跳過戰鬥使用次數",
        "Reset": "重置",
        "Catseyes": "貓眼石",
        "Catfruit": "貓薄荷",
        "Catamins": "喵力達",
        "Battle Items": "戰鬥道具",
        "Make All Endless": "設定無限道具",
        "Other Items": "其他道具",
        "Edit Scheme Items": "編輯獸石/獸結晶",
        "Edit Labyrinth Medals": "編輯地底迷宮獎章",
        "Edit Treasure Chests": "編輯神秘寶箱",
        "Edit Event Tickets": "編輯活動轉蛋券",
        "Bulk Actions": "批量操作",
        "Unlock All Cats": "解鎖全部貓咪",
        "Max Upgrade All": "全部滿級",
        "True Form All": "全部真型態",
        "Fourth Form All": "全部第四型態",
        "Max Talents All": "全部本能解放",
        "Unlock Cat Guide": "解鎖貓咪圖鑑",
        "Get Obtainable Cats": "取得可獲取貓咪",
        "Get Unobtainable Cats": "取得異常貓咪",
        "Reset Levels": "等級歸零",
        "Lock All": "全部丟棄",
        "Includes abnormal cats, risk of ban": "包含異常，會封號",
        "Cat Storage": "貓咪倉庫",
        "Edit Special Skills": "編輯特殊能力",
        "Unlocked Slots": "解鎖編成欄位",
        "Map / Levels": "關卡 / 傳奇故事",
        "Main Story": "主線故事",
        "Clear Tutorial": "通過教學關卡",
        "Clear All Story": "通關故事章節",
        "Max All Treasures": "全寶物最大",
        "Clear All Outbreaks": "通關不死生物襲擊",
        "ITF Timed Scores": "未來篇時間積分",
        "Filibuster Reclearing": "重啟議事阻撓貓關卡",
        "Advanced Chapters": "進階章節",
        "Clear Aku Realms": "通關魔界篇",
        "Unlock Aku Realm": "解鎖魔界篇",
        "Clear Uncanny Legends": "通關真傳奇故事",
        "Clear Zero Legends": "通關傳奇故事0",
        "Clear Catamin Stages": "通關喵力達關卡",
        "Behemoth Culling": "通關超獸討伐關卡",
        "Catclaw Championships": "通關貓咪道場晉段測驗",
        "Events & Gauntlets": "活動與強襲",
        "Clear SoL": "通關傳奇故事",
        "Clear Events": "通關活動關卡",
        "Clear Collab": "通關合作關卡",
        "Clear Gauntlets": "通關強襲關卡",
        "Collab Gauntlets": "通關合作強襲關卡",
        "Clear Enigma Stages": "通關發掘關卡",
        "Towers & Scores": "風雲貓咪塔 & 分數",
        "Clear Towers": "通關風雲貓咪塔",
        "Clear Legend Quest": "通關傳奇尋寶記",
        "Challenge Score": "挑戰賽分數",
        "Dojo Score": "貓咪道場分數",
        "Edit Engineers": "編輯城堡開發隊員",
        "Edit Base Materials": "編輯城堡開發材料",
        "Gamatoto XP Level": "加碼多多經驗值/等級",
        "Gamatoto Helpers": "加碼多多隊員",
        "Ototo Cannon": "城堡開發隊貓咪砲",
        "Cat Shrine": "貓咪神社",
        "Upload Items": "上傳道具",
        "Unban Account": "解封帳號",
        "Inquiry Code": "詢問碼",
        "Fix Gamatoto Crash": "修復加碼多多崩潰",
        "Fix Ototo Crash": "修復貓咪砲崩潰",
        "Fix Time Errors": "修復時間錯誤",
        "Fix Officer Pass Crash": "修復通行證崩潰",
        "Unlock Equip Menu": "解鎖裝備選單",
        "Reset Gambling Events": "重置賭場活動",
        "Set Restart Pack": "設定回歸禮包",
        "Edit Enemy Guide": "編輯敵人圖鑑",
        "Edit User Rank Rewards": "領取等級排行獎勵",
        "Edit Gold Pass": "編輯金牌會員",
        "Edit Medals": "編輯勳章",
        "Edit Missions": "編輯任務",
        "Playtime": "遊玩時間",
        "Own": "擁有",
        "Set": "設定",
        "Gacha Seeds": "轉蛋種子",
        "Rare Gatya Seed": "稀有轉蛋種子碼",
        "Normal Gatya Seed": "一般轉蛋種子碼",
        "Event Gatya Seed": "活動轉蛋種子碼",
        "Configuration": "程式設定",
        "Save Config": "儲存設定",
        "Enabled": "啟用",
        "Disabled": "停用",
        "Convert": "轉換",
        "UI Language": "界面語言",
    },
}


def get_translator(lang: str):
    lang = lang if lang in _TRANSLATIONS else "en"
    table = _TRANSLATIONS[lang]
    en_table = _TRANSLATIONS["en"]

    def t(text: str) -> str:
        if lang == "en":
            return text
        return table.get(text, en_table.get(text, text))

    return t
